### PR TITLE
Github PR Comment Demo

### PR DESCRIPTION
**Pull request by ParadoxARG**
Trying the GitHubPR Comment Task!

### CODE REVIEW

**Comment by ParadoxARG** [comment]
r
This is a text example for the demo

**Comment by ParadoxARG** [comment]
r
This is a text example for the demo

**Comment by ParadoxARG** [comment]
This is a text example for the demo

**Review by VictorGrycuk — APPROVED** [review]

**Comment by ParadoxARG** [comment]
This is a text example for the demo

**Pull request closed without merging**
