### PR TITLE
[ApiCompat] Refactor of ApiCompat Task

### PR DESCRIPTION
**Pull request by enzocano**
## Changes

- Add `build` script.
- Add `eslint` as prebuild script.
- Add TypeScript as devDependency.
- Change the structure of project to use `./src` folder for `.ts` files and `./lib` folder for `.js` files.
- Fix lint issues.
- Fixes in the format of some files.

 ## Test
> NOTE: I use [this](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#run-the-task) guide to debug the task.

I debugged the code with `VSCode` and use:
- `./Tasks/ApiCompat/source` as a root directory.
- The following `launch.json` configuration.
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\lib\\index.js",
            "env": {
                "INPUT_CONTRACTSROOTFOLDER":"C:\\Projects\\southworkscom\\SOUTHWORKS-azure-pipelines-tasks\\Tasks\\ApiCompat\\tests\\4.2.2",
                "INPUT_IMPLFOLDER":"C:\\Projects\\southworkscom\\SOUTHWORKS-azure-pipelines-tasks\\Tasks\\ApiCompat\\tests\\4.3.1",
                "INPUT_CONTRACTSFILENAME":"Microsoft.Bot.Builder.dll",
            }
        }
    ]
}
```

And I got the following results

image

### CODE REVIEW

**Comment by VictorGrycuk** [comment]
Thank you for these changes @enzocanoo.
I just tested it on Azure Pipelines and it works, :shipit:

**Review by VictorGrycuk — APPROVED** [review]

**Review by ParadoxARG — COMMENTED** [review]
Awesome improvements! We are going to hold these changes as we are going to apply a branching strategy. As soon as we have our Development branch we will be merging this there.

**Comment by ParadoxARG** [comment]
@enzocanoo can you change your PR base to the ApiCompat/release/0.2 branch, please?

**Comment by enzocano** [comment]
@ParadoxARG done!

**Pull request merged**
